cristianbote/goober

src/__tests__/styled.test.js
src/styled.js

Implemented the change for CSS we discussed. styled itself now knows how to handle the "no tag" situation. File size is as follows:

css now returns a className instead of a function

---

src/__tests__/styled.test.js
src/core/__tests__/hush.test.js
src/core/hush.js
src/core/parser/__tests__/parse.test.js
src/core/parser/parse.js
src/core/style/get-class-name.js
src/core/style/sheet.js
src/styled.js

This is addressing the support for object styled from #14 
```js
import { css, styled } from 'goober';
const Foo = css({
"text-align": "center",
padding: 0
});
// or with styled
const Baz = styled("button")({
background: "red",
"&:active": {
"color": "blue"
}
});
```
`+18B`

Object style poc

---

package-lock.json
package.json
src/goober.d.ts
typings.json

This adds a `goober.d.ts` file to the `/src` directory. Also changed was adding `typings.json` to the files array, and adding reference the the project types in the `package.json`.
This is a fairly rudimentary pass at adding types. CSS properties are not checked for to ensure that they are passed proper values.
Also, my use case is the vanilla implementation, not using styled components. I believe they should still work, but overrides for `react` and `preact` implementations may be required.

Adding TS types definition file.

---

src/styled.js

When using the `styled(tag)` function, the props passed to the component are assigned to `_ctx.p` and new properties are assigned to this object. However, `_ctx.p` is unable to be extended, due to `preventExtensions`. This results in an error `cannot add property className, object is not extensible`.
Creating a new object and assigning the props to it, will result in an extensible object again.

Create a new object and assign props to it for a new extensible object

---

src/core/__tests__/parse.test.js
src/core/parse.js

Alrighty, more golfing! 🏌 
This PR drops the `JSON.stringify` for flattening the `@keyframes` and `@font-face` and use `parse` with special args. By doing that, the perf increases.
Also, this is so awesome cause that would mean we could support more stuff.
Shaves `-15B`

(golf) Drop the stringify from parse (-15B)

---

src/core/hash.js

This pull request makes a small change to `src/core/hash.js`, removing a piece of code that is a remnant on an older approach that's not used anymore (based on a chat discussion with @cristianbote).

Remove an now-unnecessary code remnant

---

goober.d.ts
ts-tests/test-api.tsx

This PR fixes two issues:
Currently, TypeScript will incorrectly report `styled(InnerGooberComponent)` as invalid since it expects the type of `tag` to be a string. This will error when nesting components together. We add a Union type to allow nesting components.
As well, related to #80,  TypeScript will complain that the type of the VDom element returned by `styled` is incompatible since it does not have a children prop. From https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843 it seems like the best way to fix this is to add a children prop to the type.

Fix typings for nested styled components and empty props

---

src/__tests__/integrations.test.js
src/core/__tests__/to-hash.test.js
src/core/to-hash.js

This pull request modifies `to-hash.js` to return _unsigned_ 32-bit integer values. The multiplication constant is now 101 and the initial value for hash a non-zero (11).
The constants are chosen pretty arbitrarily by what seems to give good results, as long as the multiplier is a prime (or at least a prime relative to 2^n).
The tests are modified accordingly.

Modify hashing (use uint32 results, add an initial value & new multiplier)

---

packages/babel-plugin-transform-goober/README.md
packages/babel-plugin-transform-goober/__tests__/index.test.js
packages/babel-plugin-transform-goober/index.js
packages/babel-plugin-transform-goober/package.json

This pull request is based on issue #69 and chat discussions with @cristianbote and @JoviDeCroock. It adds a Babel plugin called babel-plugin-transform-goober under `/packages/babel-plugin-transform-goober`. The plugin is for rewriting [styled-components](https://styled-components.com/)-like `styled.<tagName>` syntax to `styled("<tagName>")` calls.
The plugin rewrites all expressions in the form `styled.*` to `styled("*")`. Therefore things like calls and tagged expressions also work. For example the following file:
```js
style.div;
style.div`...`;
style.div("...");
```
gets rewritten to:
```js
style("div";
style("div")`...`;
style("div")("...");
```
The plugin is enabled by adding it to the Babel configuration:
```json
{
"presets": [...],
"plugins": ["babel-plugin-transform-goober]
}
``` …

Add a Babel plugin for styled.<tagName> syntax (resembling styled-components)

---

README.md
goober.d.ts
ts-tests/test-api.tsx

On this change I updated the docs to clarify how the css(taggedTemplate) examples (#89).
I also updated the TypeScript definitions to fix some of the issues we were facing.

Update TypeScript definitions and css API docs

---

src/core/__tests__/compile.test.js
src/core/compile.js

Allow zero values inside tagged templates.
Adds `+5B` 😞

(fix) Allow zero values (#108)

---

src/core/__tests__/hash.test.js
src/core/hash.js

`glob` should be able to interpolate dynamic values passed along.

(bug) Allow glob to be parsed and appended as needed (#106)

---

goober.d.ts

Ran into some TS related errors when omitting children with a `styled` component and having `children` be optional seems to do the trick. Love this library, hope this works for you!

TS/ allow styled components to optionally use children.

---

package.json
src/__tests__/integrations.test.js
src/__tests__/styled.test.js
src/core/__tests__/parse.test.js
src/core/parse.js
src/styled.js

Adds the test for #47 and rewires the forward ref.
@lucat1 pointed out that the current forward ref implementation does not properly work if one tries to import a component before calling `setup`. Which makes total sense. So, this PR address it like this:
* ~~We have support for `styled` to be directly passed to `React.forwardRef`~~ We still have that support but `forwardRef` should be passed as second argument to `styled`.
* `setup` no longer needs the forward ref function.
This boils down to this:
```js
const Foo = styled('div', React.forwardRef)`
background: tomato;
`;
```

(chore) Revamp the fwd ref and add nested test

---

packages/gatsby-plugin-goober/gatsby-browser.js
packages/gatsby-plugin-goober/gatsby-ssr.js
packages/gatsby-plugin-goober/package.json

Adds `goober-autoprefixer` to `gatsby-plugin-goober`

(chore) Add goober-autoprefixer to gatsby plugin

---

.github/workflows/pr_build.yml
package-lock.json
package.json
packages/goober-autoprefixer/package-lock.json
packages/goober-autoprefixer/package.json

This is so `goober` will get zero dependencies needs

(chore) Move tiny-css-prefixer as a dep to goober-autoprefixer

---

packages/babel-plugin-transform-goober/README.md
packages/babel-plugin-transform-goober/__tests__/__fixtures__/123.txt
packages/babel-plugin-transform-goober/__tests__/__fixtures__/multiple.txt
packages/babel-plugin-transform-goober/__tests__/__fixtures__/space name.txt
packages/babel-plugin-transform-goober/__tests__/index.test.js
packages/babel-plugin-transform-goober/index.js
src/__tests__/styled.test.js
src/styled.js

This PR adds several features to the `babel-plugin-transform-goober` plugin.
Minifiers have a hard time knowing if a `styled()` call has a side-effect or not. To avoid generating invalid code they side with caution and won't remove unused components.
```js
// Final bundle, Foo is still there despite it not being used anywhere
const Foo = styled("div")``;
export function Bar() {
return <div />
}
```
By adding a `#__PURE__` comment just before the call expression we can signal minifiers that the next statement has no side effects.
```js
// Before minification
const Foo = /*#__PURE__*/ styled("div")``;
export function Bar() {
return <div />
}
```
After:
```js
// Final bundle, Foo is gone
export function Bar() {
return <div />
}
```
This is enabled by default as I can hardly come up with a …

Enhance babel plugin for nicer developer UX

---

src/__tests__/styled.test.js

This PR rewrites the styled test suite to rely less on heavy mocking of internals and instead they're only verifying the end result. They're basically rewritten to be proper integration tests, which should make it easier for us to experiment with internals against a stable test suite that doesn't break when we rename an internal function.
The changes here are arguably subjective. For me this makes the tests easier to follow along and they're a little shorter to write. Let me know what you think :+1: 
(The inline diff view in GitHub is a little confusing. The differences are easier to see when compared side by side)

Simplify styled test cases to use less mocking

---

src/core/__tests__/astish.test.js
src/core/astish.js

This PR adds support for parsing multiline comments inside the CSS string. Previously they were not stripped and would trip up our parser, leading to invalid CSS.

Add support for parsing multiline CSS comments

---

README.md
package-lock.json
package.json
src/__tests__/css.test.js
src/__tests__/index.test.js
src/__tests__/integrations.test.js
src/core/__tests__/hash.test.js
src/core/__tests__/parse.test.js
src/core/hash.js
src/core/to-hash.js
src/css.js
src/index.js

This one adds support for `keyframes` function, same thing as `glob` but, this one hashes the animation names so one could reuse the same animations if wanted.
Could be used in all sorts of ways, as an example:
```js
import { keyframes, css } from 'goober';
const fade = keyframes`
to {
opacity: 1;
}
`;
const cls = css`
opacity: 0.5;
&:hover {
animation: 1s ${fade} ease-out;
}
`;
```
Still need to sort out:

(feat) keyframes

---

package-lock.json
package.json
src/__tests__/integrations.test.js
src/core/__tests__/compile.test.js
src/core/compile.js

This is handling the parsing of objects inside the tagged templates, by passing the `res` from the function call to the parse method.
Fixes #186 #136

(feat) Add support for object outputs in tagged templates

---

README.md

Add an example in the `README` to showcase the `setup` with a theme.

docs: extend setup api with theme example

---

README.md

Add an example in the README to showcase the setup with a prefixer.

docs: extend setup api with prefixer example

---

goober.d.ts
ts-tests/test-api.tsx

By letting the user extend the `goober` TypeScript definitions it is possible to support theme types. Should be used in combination when using theme in `setup(X, X, theme)`.
It works as follows:
1) The user should create a declarations file, let's call it `goober.d.ts` (file name suggestions?)
```ts
import 'goober';
declare module 'goober' {
export interface DefaultTheme {
colors: {
primary: string;
};
}
}
```
2) Use it like you should normally do (but with "autocomplete")
```js
const ThemeContainer = styled('div')`
background-color: ${(props) => props.theme.colors.primary};
`;
```
`DefaultTheme` is being used as an interface of `props.theme` out of the box.
If this PR gets approved, I think this should be moved to a section in the `README`.
Inspiration: …

Add support for theme TypeScript definitions

---

goober.d.ts
ts-tests/test-api.tsx

This adds updates the type declarations adding the types second argument to `styled()` - `forwardRef`.
I believe it's not possible to make the types more specific than a function that returns `any`
Fixes #176

Add the types for forwardRef argument to styled()

---

package.json

I was trying to use `goober` with `snowpack` when I started noticing [this error](https://github.com/snowpackjs/snowpack/discussions/1421).
As mentioned in [specs](https://nodejs.org/api/packages.html#packages_package_entry_points), It seems, when `exports` is present, we can not use `main` as a fallback.
This PR should fix the usage for snowpack and modern node versions.

fix package entry points

---

goober.d.ts
ts-tests/test-api.tsx

Added missing types for `keyframes` function introduced in #181.
Closes #204

Add types for `keyframes`

---

package-lock.json
package.json
src/__tests__/integrations.test.js
src/styled.js

Everything works as expected until you try to extend an styled component. So, in order to let the props pass through, until it arrives at the _real_ tag element, we should not call the fwdProp function. 👍

(fix) makes sure the props are passed when extending

---

README.md
docs/docs/integrations/css-prop.md
docs/sidebars.js

Relates to #209 
* Adds [babel-plugin-goober-css-prop](https://github.com/agneym/babel-plugin-goober-css-prop) to the integrations list.
* Corrects link for [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros)

add babel-plugin-css-prop to integrations

---

should-forward-prop/package.json

The `types` field in `package.json `for `should-forward-prop`  is pointing to an invalid type file

fix should forward prop types reference

---

README.md
docs/docs/features/typescript.md
docs/sidebars.js

This PR adds basic typescript documentation to the README and to the Docs website. 
More specifically, it adds documentation regarding using a custom theme and defining typed prop types. In the documentation it also includes a note on defining types within Preact, but I felt this was unnecessary for the README.
I've added it under Features, but you may feel it belongs elsewhere.

Misc: Update Typescript Documentation

---

packages/gatsby-plugin-goober/gatsby-ssr.js

Support both `goober-autoprefixer` and `goober/prefixer` in `gatsby-plugin-goober`

chore: support goober prefixer in gatsby plugin

---

package.json

This came up in https://github.com/jspm/project/issues/96 on jspm.dev for react-host-toast.
react-hot-toast contains:
```js
goober = require('goober');
```
When JSPM builds for the browser, it converts the above into:
```js
import goober from 'goober';
```
Per the Node.js semantics. But then uses the browser ESM version, which doesn't export a default export.
This ensures the require version is always used for CJS requires both in the browser and Node.js. An alternative could be to provide a default export in the ESM version as well.

Give preference to require main

---

goober.d.ts

When utilising TypeScript with Goober, and the array method of adding CSS attributes, like so:
```ts
import { styled } from 'goober'
styled('div')([{
color: 'blue'
}])
```
TypeScript complains that an array cannot be used, however this is valid Goober syntax (see screenshot below).
This PR adds the option for an array to passed as `CSSAttribute[]` to stop TypeScript complaining.

Add Typings for Arrays of CSS Attributes

---

README.md
global/src/__tests__/global.test.js
src/__tests__/css.test.js
src/__tests__/index.test.js
src/css.js
src/index.js

Reverts cristianbote/goober#253 until a major version, since it's a API deprecation.

Revert "Remove glob from core"

---

prefixer/README.md

Fixed the description in the README.

README mentions tiny-css-prefixer but style-vendorizer is used (#270)

---

goober.d.ts
src/__tests__/css.test.js

- Fix #275 
- Add test to ensure functions are valid as array items for `css(...)`

fix: Missing TS types for `styled` function (#275)

---

README.md
docs/docs/api/setup.md

Adds the following line to the docs on `setup()`:
The call to `setup()` should occur once only. It should be called in the entry file of you project.

Updates docs regarding setup() - once only - in entry file.

---

src/core/astish.js

This pull request shaves 5 bytes out of the minified + gzipped `goober.js.gz` file. The changes are all made to the `ruleClean` regular expression in the `src/core/astish.js` file:
* Change `[\s\S]` to `[^]`. The original `[\s\S]` is there to match any character (I think), and `[^]` also means that (per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes).
* Change `\s{2,}` to `\s\s+`.
* Remove the `m` (multiline) flag from the regex, as it seems the regular expression is not dependent on the functionality that the multiline flag affects.

Rephrase a regexp in astish.js to shave off 5 bytes from the built bundle

---

src/core/get-sheet.js
src/core/to-hash.js

From my local build, it's shave about >3b from `goober.js.gz` (and also from another file), let's see how the results in action.
What I'm doing:
1. Remove usage of `l` in `to-hash` since looks like it's just container for `str.length`
2. Remove usage of `sheet` in `get-sheet.js` since I think we could continue without using it

Remove some variable usage

---

src/core/parse.js
src/styled.js

g flag is counter-productive for .test() method with single use regex instances. one match should be conclusive.

remove g flag from regex test

---

goober.d.ts

extractCss() can receive a target argument, but d.ts does not support it.
https://github.com/cristianbote/goober#extractcsstarget

fix: Add a target argument to the extractCss typing

---

src/core/get-sheet.js

Glad I found out about the **The Great Shave Off Challenge** as I played with the idea that I wanted to contribute.
Here is a small optimization of the condition in the `getSheet` function, which saves some characters and removes exclamation mark to make compression better.
**Before:**
```
1173 B: goober.js.gz
1065 B: goober.js.br
1181 B: goober.modern.js.gz
1074 B: goober.modern.js.br
1181 B: goober.esm.js.gz
1074 B: goober.esm.js.br
1241 B: goober.umd.js.gz
1120 B: goober.umd.js.br
```
**Now:**
```
1165 B: goober.js.gz
1057 B: goober.js.br
1174 B: goober.modern.js.gz
1065 B: goober.modern.js.br
1174 B: goober.esm.js.gz
1065 B: goober.esm.js.br
1239 B: goober.umd.js.gz
1115 B: goober.umd.js.br
```
Difference: **-8B**
**Characters:**
Before: 2153
Now: 2150
**Where savings made:**
- …

Code golf getSheet (-8B)

---

goober.d.ts

The type doesn't seem correct, the docs: https://goober.js.org/api/setup. Noticed, while I was working on https://github.com/mui-org/material-ui/pull/27776.

Fix forwardProps type

---

package-lock.json
package.json
src/__tests__/integrations.test.js
src/styled.js

Fix the behaviour of extending with as when mixing multiple values

---

goober.d.ts

Closes #409 
Adds support for the [`defaultProps`](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) property, adding it to the `StyledVNode` type.

adds `defaultProps` to `StyledVNode` type

---

global/package-lock.json
global/package.json
prefixer/package-lock.json
prefixer/package.json
should-forward-prop/package-lock.json
should-forward-prop/package.json

Sorry, my fault. I'm not sure if I was running Microbundle weirdly or if I just didn't see the output. As [you can see here](https://www.runpkg.com/?goober@2.1.3/global/dist/goober-global.cjs.js), subpackages were built with `.cjs.js` extensions due to a bug in older Microbundle versions.
Would really recommend moving to a mono-repo setup and install Microbundle just once. Managing 4 separate lock files at once seems a bit fragile. Microbundle has good support of being ran in other directories, as can be seen in [preact](https://github.com/preactjs/preact/blob/4f08ae4d607964ae8222e910d3b209def75626b0/package.json#L96). I haven't used NPM's workspaces, but I know Yarn (1)'s works quite well so I imagine NPM is a similar story.

fix: Microbundle builds

---

src/core/__tests__/parse.test.js
src/core/parse.js

~*Untested*~
Closes #423 
Skips formatting custom CSS properties using a lax check that a property's key does not begin with `--`.

skip parsing and formatting custom CSS properties

---

src/core/__tests__/astish.test.js
src/core/astish.js

(fix) Replace newlines with empty space

---

README.md

Since [in other sections of these docs](https://github.com/cristianbote/goober#ssr-1) we are using `import styled from`, it makes it seem that this is supported by goober, while it's not actually supported. So added it to the table of things that are not supported.

Added note about unsupported `import styled from`

---

package.json

PR exports types in package.json file. 
When using new `bundler` option for `moduleResolution` in `tsconfig.json` as part of TypeScript V5, you will receive the following error: 
```
error TS7016: Could not find a declaration file for module 'goober'. '.../node_modules/goober/dist/goober.modern.js' implicitly has an 'any' type.
There are types at '.../node_modules/goober/goober.d.ts', but this result could not be resolved when respecting package.json "exports". The 'goober' library may need to update its package.json or typings.
```

Export types in package.json

---

package.json

Defines types in the exports map, so that imports work when leveraging the newer moduleResolution tsconfig values (nodenext, node16, bundler).

export type in package.json should-forward-prop path

---

goober.d.ts

The global `JSX` type is deprecated in React 18.3 and removed in React 19 RC. This PR changes the code to use the supported `React.JSX` syntax instead.

Replace `JSX` with `React.JSX`

---

src/__tests__/integrations.test.js
src/core/parse.js

Expand the parser to also include multiple selector inside of `foo:has(one, two) {}`
Fixes #596

(fix) Fixes the :has and other selector when used with multiple (fixes #596)

---

README.md
package.json
src/core/get-sheet.js

Fixes #471
This PR adds Content Security Policy (CSP) nonce support to goober, making it compatible with strict CSP policies that require style-src 'nonce-...'.
- Multi-source nonce detection: goober now automatically checks for nonces from three sources in priority order:
a. Explicit setNonce() call
b. Vite convention: <meta property="csp-nonce"> tag
c. Webpack convention: window.__webpack_nonce__
- New export: setNonce() function for explicit nonce control
- Documentation: Added CSP section to README explaining all three methods
```
// Method 1: Explicit control
import { setNonce } from 'goober';
setNonce('your-nonce-here');
// Method 2: Vite (automatic detection)
// <meta property="csp-nonce" nonce="your-nonce-here" />
// Method 3: Webpack (automatic detection)
// …
```

Added Content Security Policy support
