src/__tests__/css.test.js
src/__tests__/styled.test.js
src/core/__tests__/hush.test.js
src/core/hush.js
src/core/parser/get-css.js
src/core/style/__tests__/get-class-name.test.js
src/core/style/get-class-name.js
src/css.js
src/styled.js

This is addressing #10.
So, the idea was to add a `createGlobal` function, which would basically be `styled` call. So, that would just add size to the bundle.
```js
// Define the global style
styled("global")`
html,
body {
padding: 0;
background: red;
}
`
```
`+19B`

Add global style

---

goober.d.ts

Updated the typings to support camelCase parsing #31. Using the more general Properties.

Typings - Update from PropertiesHyphen to Properties

---

.prettierignore
.prettierrc
README.md
benchmarks/perf.js
goober.d.ts
package-lock.json
package.json
src/__tests__/css.test.js
src/__tests__/index.test.js
src/__tests__/integrations.test.js
src/__tests__/styled.test.js
src/core/__tests__/astish.test.js
src/core/__tests__/compile.test.js
src/core/__tests__/get-sheet.test.js
src/core/__tests__/hash.test.js
src/core/__tests__/parse.test.js
src/core/__tests__/to-hash.test.js
src/core/__tests__/update.test.js
src/core/astish.js
src/core/compile.js
src/core/get-sheet.js
src/core/hash.js
src/core/parse.js
src/core/to-hash.js
src/core/update.js
src/css.js
src/index.js
src/styled.js
tests/setup.js
ts-tests/test-api.tsx

As a contributor I found extremely difficull to write any code and then format it by hand...
This PR adds prettier, which is a common standard used across oss projects.
- if you're ok with this, I'll add husky and lint-staged so everything will be formatted on every commit.
Lemme know.
cheers

chore: add prettier and format script task

---

README.md

this expands features list, with those that are not obvious from docs/examples 💪(but are present)

docs: extend features list

---

src/core/parse.js

as thr prev PR, just for smaller size.

---

goober.d.ts
ts-tests/test-api.tsx

This one fixes the typings for multiple functions inside the tagged template. (#91)

(fix) Fix typing for multiple tagged templates functions (Fixes #91)

---

README.md

Hey, I create a demo for fre, there are people who want to use goober in fre.

add fre codesanbox demo

---

packages/gatsby-plugin-goober/package.json
packages/goober-autoprefixer/package.json

(chore) Publish the autoprefixer

---

README.md

Added example of using `css` with JSON/Object

Using `css` with object

---

src/core/hash.js

Golf stringify function -3B

---

package-lock.json
package.json
packages/goober-autoprefixer/package.json
src/core/__tests__/hash.test.js
src/core/__tests__/parse.test.js
src/core/__tests__/to-hash.test.js
src/core/hash.js
src/core/parse.js
src/core/to-hash.js
src/core/update.js

This actually tackles the nested parse improvements from #166 and other issues. Also this one enables the `@support` rule and the rest of the bunch. Test pending.
This kinda adds a few bytes to the size but it's totally worth it. I'll explore more though.

(chore) parse improvements

---

package-lock.json
package.json
src/core/__tests__/parse.test.js
src/core/parse.js

(fix) true nested handler

---

package.json

Improve package quality test by adding an exports map and a more declarative repository url.

(chore) Improve package quality score by adding exports map

---

README.md
package.json
src/__tests__/css.test.js
src/__tests__/integrations.test.js
src/css.js

This is a new way, for goober, to define your conditional styling based on an array of objects or array of functions.
cc @ben-rogerson

(feat) Conditional styles with array as argument

---

src/__tests__/integrations.test.js
src/css.js

(fix) Make sure reduce works on a new object

---

README.md

Add notes for `css` section. (refs #158)

(docs) Notes about css and extractCSS usage

---

goober.d.ts

Addition to #193 
Add TypeScript theme support for styled components, atm there is only support for native html elements

chore: add typescript theme for styled components

---

README.md
global/babel.config.js
global/jest.setup.js
global/package-lock.json
global/package.json
global/src/__tests__/global.test.js
global/src/index.js
package-lock.json
package.json

Introducing the `goober/global` addon for handling the global styles properly! 🎉 
From now the recommended way, to add global styles, is through the `createGlobalStyles` method.

(feat) Move glob to global addon

---

README.md

Added info about preact cli plugin

---

README.md

Add additional forward prop info in `README`

docs: add transient forward prop in readme

---

README.md
docs/docs/introduction.md
src/core/__tests__/get-sheet.test.js
src/core/get-sheet.js

This change increases the SSR perf at least 3x while keeping the browser env consistent.

(feat) Increase the SSR perf

---

global/global.d.ts
package.json

* Fix reference to the `goober/global` type 
* Fix `createGlobalStyles` type

Fix global type

---

prefixer/__tests__/index.test.js
prefixer/src/index.js

(bug) Fix the sticky prefixer for position

---

.github/workflows/pr_build.yml
global/jest.setup.js
global/package-lock.json
global/package.json
global/src/__tests__/__snapshots__/integration.test.js.snap
global/src/__tests__/global.test.js
global/src/__tests__/integration.test.js
global/src/index.js

(fix) createGlobalStyles should be theme aware

---

README.md

Hello @cristianbote,
here I have fixed just a missing import in the main README.md docs
just checked that it works properly https://codesandbox.io/s/react-goober-forked-2bnec?file=/src/index.js
have a nice day :)

✏️ README.md: added missing import

---

packages/gatsby-plugin-goober/gatsby-ssr.js
packages/gatsby-plugin-goober/package.json

(fix) Change the gatsby-plugin-goober to esm for ssr

---

README.md
docs/docs/api/styled.md

Based on CB's request here
https://github.com/cristianbote/goober/issues/257

Add forward ref function example to API docs

---

README.md
docs/docs/integrations/gatsby.md

As per the gatsby-plugin-goober readme.

Added goober to Gatsby plugin install instructions

---

README.md
docs/docs/introduction.md
package-lock.json
package.json

Add tradeoff and comparison

---

README.md

👋 Hey! I came over from Twitter via The Great Shave Off. 
Didn't end up shaving any bytes, but I did polish the README a little bit. I tried to make sure not to change any semantics or tone, just grammar and typos.

Small grammar and typo fixes in README

---

src/core/parse.js

By reusing the `key` we could shave off `-4B` I think 🤔

Reuse the key var to shave off -4B

---

global/global.d.ts

cc. https://github.com/cristianbote/goober/issues/246#issuecomment-876348623

add Theme type to createGlobalStyles literal function callback

---

goober.d.ts

cc. https://github.com/cristianbote/goober/issues/338
Would be great to have this and my other 2 PRs merged and a new version published if you're happy with them. Can test using this package `@jlalmes/goober@2.0.38-fix.5`.
Great package btw! 🎉

added type support for babel-plugin-transform-goober

---

src/__tests__/styled.test.js
src/styled.js

Fixes: #349 #332 https://codesandbox.io/s/goofy-mountain-uvlkn?file=/src/App.js

Fix issue with cyclical "as" prop

---

global/package.json
macro/package.json
package.json
should-forward-prop/package.json

License information has been changed from ISC to MIT.

mod license MIT from ISC

---

goober.d.ts
package-lock.json
package.json
ts-tests/test-api.tsx

Fix the type for missing display name

---

package.json
src/core/__tests__/parse.test.js
src/core/parse.js

Fix bad transform for special selectors

---

goober.d.ts
ts-tests/test-api.tsx

Fix types for missing as definition

---

docs/docs/api/styled.md
goober.d.ts
src/core/__tests__/parse.test.js
src/core/parse.js

@cristianbote First, Thank you for this great library.
This feature can handle following case.
```js
const Btn = styled("button")((props) => ({
borderRadius: props.rounded
}));
<Btn rounded="2px" />; // => { borderRadius: "2px" }
let isRounded = false
<Btn rounded={isRounded ? "4px" : null} />; // => { borderRadius: null }
<Btn>; // => { borderRadius: undefined }
```
This **should** work for something like this.
```js
const Btn = styled("button")(
(props) => `
border-radius: ${props.rounded};
`
);
<Btn rounded="2px" />; // => `border-radius: 2;`
let isRounded = false
<Btn rounded={isRounded ? "4px" : null} />; // => `border-radius: null;`
<Btn>; // => `border-radius: undefined;`
```
Thanks.

[feature] Remove empty values of properties.

---

package.json

Update csstype peerDependency to v3.0.10

---

prefixer/LICENSE
prefixer/package-lock.json
prefixer/package.json

Add license to prefixer package for compliance reason
